# Generated by Django 3.2.9 on 2021-12-06 03:12

from django.db import migrations, models
import psicologo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=65)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('local_number', models.IntegerField()),
                ('licensed', models.CharField(max_length=35)),
                ('image', models.ImageField(blank=True, null=True, upload_to=psicologo.models.professional.nameFile)),
                ('description', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=35)),
            ],
        ),
    ]
