# Generated by Django 3.2.9 on 2021-12-06 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='professional',
            table='professional',
        ),
    ]
